### ISSUE TITLE
Crash when using importlib.metadata.version

### ISSUE THREAD

**Issue by gsemet** [ClericPy/zipapps#28]
Hi

When using
```python
from importlib.metadata import version
version("name_of_my_package")
```
I get a crash `importlib.metadata.PackageNotFoundError: No package metadata was found for name_of_my_package`

I first create the wheel of my package and then create the 
```
   zipapps --output dist/$(PACKAGE_NAME).pyz -u=AUTO
        -p '/usr/bin/env python3'
        -m name_of_my_package.cli:cli 
        -r dist/prod-requirements.txt 
        dist/name_of_my_package-*.whl
```

I think name_of_my_package.whl is well installed I see it in the pip install output, but it seems like the importlib does not find it when executed in the pyz generated by zipapps. It works with shiv.

**Comment by ClericPy** [comment]
try use `-u=*` to unzip all the files, this is similar to shiv may make some sense

**Comment by TsXor** [comment]
This is because zipapps does not include package metadata.
For example, let's run `python -m zipapps -o psutil.pyz -u AUTO psutil` and take a look inside generated `psutil.pyz`.
You'll find that only module directory `psutil` is present, but metadata directory (in my case `psutil-5.9.2.dist-info`) is missing. That's why `importlib.metadata` complains.
To fix that, you can use lazy install, which installs required packages at runtime.
Alternatively, you can tell zipapps to use a specific cache directory and copy package metadata to there ahead of time.
